name: tally_clone
description: tally_clone

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_glow: ^0.3.0
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  assets:
    - assets/
  fonts:
    - family: f1
      fonts:
        - asset: assets/fonts/regular_font_f1.OTF
          weight: 400
